from enum import StrEnum


class TemplateStatus(StrEnum):
    UNSUPPLIED = "UNSUPPLIED"
    SUPPLIED = "SUPPLIED"


class SampleStatus(StrEnum):
    SAMPLE_COMMUNICATION = "SAMPLE_COMMUNICATION"
    FACTORY_COMMUNICATION = "FACTORY_COMMUNICATION"
    SAMPLE_PRODUCING = "SAMPLE_PRODUCING"
    SAMPLE_COMPLETED = "SAMPLE_COMPLETED"
    SAMPLE_DELIVERY = "SAMPLE_DELIVERY"
    PRODUCT_CONFIRMED = "PRODUCT_CONFIRMED"


class FormalStatus(StrEnum):
    ORDER_COMMUNICATION = "ORDER_COMMUNICATION"
    FACTORY_COMMUNICATION = "FACTORY_COMMUNICATION"
    ORDER_PRODUCING = "ORDER_PRODUCING"
    ORDER_COMPLETED = "ORDER_COMPLETED"
    DELIVERED_TO_CUSTOMER = "DELIVERED_TO_CUSTOMER"


SAMPLE_FLOW = list(SampleStatus)
FORMAL_FLOW = list(FormalStatus)

SAMPLE_FLOW_TEXT = {
    "SAMPLE_COMMUNICATION": "样品沟通",
    "FACTORY_COMMUNICATION": "工厂沟通",
    "SAMPLE_PRODUCING": "样品制作中",
    "SAMPLE_COMPLETED": "样品制作完成",
    "SAMPLE_DELIVERY": "顾客送样",
    "PRODUCT_CONFIRMED": "成品确定",
}

FORMAL_FLOW_TEXT = {
    "ORDER_COMMUNICATION": "订单沟通",
    "FACTORY_COMMUNICATION": "工厂沟通",
    "ORDER_PRODUCING": "订单制作中",
    "ORDER_COMPLETED": "订单制作完成",
    "DELIVERED_TO_CUSTOMER": "送达顾客",
}
